Repository GroovyMC/ModsDotGroovy, pull requests merged in 2022-12, with the labels that each got.

#13 Better quilt support
  Test/build.gradle
  Test/src/main/resources/mods.groovy
  gradle.properties
  src/lib/groovy/ModsDotGroovy.groovy
  src/lib/groovy/modsdotgroovy/ImmutableModInfo.groovy
  src/lib/groovy/modsdotgroovy/ImmutableQuiltModInfo.groovy
  src/lib/groovy/modsdotgroovy/ModInfoBuilder.groovy
Labels: enhancement, quilt

#14 Smart updateJsonUrl inference feature
  Test/src/main/resources/mods.groovy
  build.gradle
  gradle.properties
  src/lib/groovy/ModsDotGroovy.groovy
Labels: enhancement, forge

#17 Fix displayUrl and updateJsonUrl generation
  README.md
  Test/build.gradle
  Test/gradle.properties
  Test/src/main/resources/mods.groovy
  gradle.properties
  src/lib/groovy/ModsDotGroovy.groovy
Labels: bug, forge
